In [ ]:
import pandas as pd
from InfoCreate import InfoCreate

aux = InfoCreate(["aapl_tsla_daily_2024.parquet"], ["AAPL", "TSLA"], "2024-01-02 09:00:00+00:00", "2024-01-06 00:59:00+00:00", None, 0.01)

df = aux.data

In [2]:
sym = df.columns.get_level_values("symbol").unique()
sym

Index(['AAPL', 'TSLA'], dtype='object', name='symbol')

In [96]:
data = df.copy()
data

symbol                         AAPL                                          \
                                ask       bid     close      high       low
timestamp
2024-01-02 09:00:00+00:00  191.5300  191.5100  190.2000  191.5200  190.0000
2024-01-02 09:01:00+00:00  190.1200  190.1000  190.0000  190.1300  190.0000
2024-01-02 09:02:00+00:00  189.9100  189.8900  189.8200  189.9000  189.8200
2024-01-02 09:03:00+00:00  189.8800  189.8600  189.8700  189.8700  189.8000
2024-01-02 09:04:00+00:00  189.9100  189.8900  189.9000  189.9500  189.9000
...                             ...       ...       ...       ...       ...
2024-01-06 00:55:00+00:00  180.8100  180.7900  180.8000  180.8000  180.8000
2024-01-06 00:56:00+00:00  180.8101  180.7901  180.8001  180.8001  180.8001
2024-01-06 00:57:00+00:00  180.8200  180.8000  180.7800  180.8100  180.7800
2024-01-06 00:58:00+00:00  180.7600  180.7400  180.7400  180.7600  180.7400
2024-01-06 00:59:00+00:00  180.7900  180.7700  180.7800  180.7800  180.7500

symbol                                                                  TSLA  \
                               open trade_count   volume        vwap     ask
timestamp
2024-01-02 09:00:00+00:00  191.5200       612.0  18933.0  190.241493  248.06
2024-01-02 09:01:00+00:00  190.1100       425.0   8562.0  190.088775  250.81
2024-01-02 09:02:00+00:00  189.9000       129.0   5355.0  189.823988  250.64
2024-01-02 09:03:00+00:00  189.8700        83.0   4405.0  189.859107  250.75
2024-01-02 09:04:00+00:00  189.9000        87.0   2225.0  189.916633  250.72
...                             ...         ...      ...         ...     ...
2024-01-06 00:55:00+00:00  180.8000        30.0   1024.0  180.800000  237.35
2024-01-06 00:56:00+00:00  180.8001        13.0    267.0  180.800100  237.34
2024-01-06 00:57:00+00:00  180.8100        41.0   1774.0  180.791558  237.36
2024-01-06 00:58:00+00:00  180.7500        43.0    887.0  180.747123  237.37
2024-01-06 00:59:00+00:00  180.7800        41.0   2149.0  180.758386  237.41

symbol                                                               \
                              bid     close    high     low    open
timestamp
2024-01-02 09:00:00+00:00  248.04  250.8800  250.88  248.05  248.05
2024-01-02 09:01:00+00:00  250.79  250.6400  250.80  250.49  250.80
2024-01-02 09:02:00+00:00  250.62  250.7400  250.74  250.55  250.63
2024-01-02 09:03:00+00:00  250.73  250.8700  250.88  250.74  250.74
2024-01-02 09:04:00+00:00  250.70  250.7500  250.75  250.71  250.71
...                           ...       ...     ...     ...     ...
2024-01-06 00:55:00+00:00  237.33  237.3300  237.38  237.33  237.34
2024-01-06 00:56:00+00:00  237.32  237.3899  237.39  237.32  237.33
2024-01-06 00:57:00+00:00  237.34  237.3700  237.37  237.30  237.35
2024-01-06 00:58:00+00:00  237.35  237.4000  237.40  237.36  237.36
2024-01-06 00:59:00+00:00  237.39  237.4000  237.40  237.39  237.40

symbol
                          trade_count   volume        vwap
timestamp
2024-01-02 09:00:00+00:00       490.0  45689.0  248.641496
2024-01-02 09:01:00+00:00       267.0   9704.0  250.620665
2024-01-02 09:02:00+00:00       239.0  24077.0  250.655699
2024-01-02 09:03:00+00:00       151.0  19369.0  250.841022
2024-01-02 09:04:00+00:00        83.0   2055.0  250.740588
...                               ...      ...         ...
2024-01-06 00:55:00+00:00        40.0   1515.0  237.357500
2024-01-06 00:56:00+00:00        71.0   3585.0  237.365234
2024-01-06 00:57:00+00:00        52.0   4815.0  237.339598
2024-01-06 00:58:00+00:00        51.0   3756.0  237.380920
2024-01-06 00:59:00+00:00        70.0   5467.0  237.392615

[3723 rows x 18 columns]

In [98]:
data['AAPL']['open']

timestamp
2024-01-02 09:00:00+00:00    191.5200
2024-01-02 09:01:00+00:00    190.1100
2024-01-02 09:02:00+00:00    189.9000
2024-01-02 09:03:00+00:00    189.8700
2024-01-02 09:04:00+00:00    189.9000
                               ...
2024-01-06 00:55:00+00:00    180.8000
2024-01-06 00:56:00+00:00    180.8001
2024-01-06 00:57:00+00:00    180.8100
2024-01-06 00:58:00+00:00    180.7500
2024-01-06 00:59:00+00:00    180.7800
Name: open, Length: 3723, dtype: float64

In [94]:
import numpy as np
sym = data.columns.get_level_values("symbol").unique()
logBars = np.log(data.loc[:, (sym, ["close", "high", "low", "open"])])
startTick = logBars.iloc[0]
a1 = logBars.loc[:, (sym, "open")]
a2 = logBars.loc[:, (sym, "close")]
a3 = logBars.loc[:, (sym, "high")]
a4 = logBars.loc[:, (sym, "low")]

relGap = a1.to_numpy() - a2.shift().to_numpy()
relOpen = a1.to_numpy() - a2.to_numpy()
relHigh = a3.to_numpy() - a2.to_numpy()
relLow = a4.to_numpy() - a2.to_numpy()
l = len(a1) - 1
ids = np.arange(l)
#perm = self.rng.permutation(ids)
#perm2 = self.rng.permutation(ids)
perm = perm2 = ids
relLow = relLow[1:][perm]
relOpen = relOpen[1:][perm]
relHigh = relHigh[1:][perm]
relGap = relGap[1:][perm2]

aux = np.zeros((l + 1, 4 * len(sym)))
aux[0] = startTick.to_numpy()
for i in range(len(sym)):
    aux[1:, i * 4] = aux[0, i * 4] + np.cumsum(relGap[:, i] - relOpen[:, i], axis=0)
    aux[1:, i * 4 + 1] = relHigh[:, i] + aux[1:, i * 4]
    aux[1:, i * 4 + 2] = relLow[:, i] + aux[1:, i * 4]
    aux[1:, i * 4 + 3] = relOpen[:, i] + aux[1:, i * 4]

aux = np.exp(aux)
ans = data.copy()
ans.loc[:, (sym, ["close", "high", "low", "open"])] = aux

In [95]:
np.allclose(ans.to_numpy(), data.to_numpy())

True

In [87]:
aux[0] = startTick.to_numpy()
for i in range(len(sym)):
    aux[1:, i * 4 + 3] = relGap[:, i]
    aux[1:, i * 4] = relClose[:, i]
    aux[1:, i * 4 + 1] = relHigh[:, i]
    aux[1:, i * 4 + 2] = relLow[:, i]
aux[0, 4]

np.float64(5.513630338747058)

In [88]:
for i in range(1, l + 1):
    for i2 in range(len(sym)):
        aux[i, i2 * 4 + 3] = aux[i - 1, i2 * 4] + aux[i, i2 * 4 + 3]
        aux[i, i2 * 4] = aux[i, i2 * 4 + 3] + aux[i, i2 * 4]
        aux[i, i2 * 4 + 1] = aux[i, i2 * 4 + 3] + aux[i, i2 * 4 + 1]
        aux[i, i2 * 4 + 2] = aux[i, i2 * 4 + 3] + aux[i, i2 * 4 + 2]

aux

array([[5.25499224, 5.24807615, 5.25499224, ..., 5.52497474, 5.52497474,
        5.51363034],
       [5.2481841 , 5.2481841 , 5.2481841 , ..., 5.52493565, 5.52533617,
        5.52493565],
       [5.24788026, 5.24788026, 5.24788026, ..., 5.52472687, 5.52472687,
        5.52472687],
       ...,
       [5.19633819, 5.19628348, 5.19633819, ..., 5.46909772, 5.46955741,
        5.46909772],
       [5.19628348, 5.19702947, 5.19705709, ..., 5.46825789, 5.46910535,
        5.46817311],
       [5.19705529, 5.19728082, 5.19738532, ..., 5.46974648, 5.46995312,
        5.46813328]])

In [89]:
aux = np.exp(aux)
aux

array([[191.52      , 190.2       , 191.52      , ..., 250.88      ,
        250.88      , 248.05      ],
       [190.2205333 , 190.2205333 , 190.2205333 , ..., 250.87019521,
        250.97069202, 250.87019521],
       [190.16274591, 190.16274591, 190.16274591, ..., 250.8178219 ,
        250.8178219 , 250.8178219 ],
       ...,
       [180.60967081, 180.59979063, 180.60967081, ..., 237.24603494,
        237.35511813, 237.24603494],
       [180.59979063, 180.7345666 , 180.7395583 , ..., 237.04687135,
        237.24784369, 237.02677412],
       [180.7392325 , 180.78      , 180.79889226, ..., 237.4       ,
        237.44905972, 237.01733416]])

In [90]:
test = data.copy()
test.loc[:, (sym, ["open", "close", "high", "low"])] = aux

In [13]:
''''
ids = np.arange(l)
perm = np.random.permutation(ids)
relLow = relLow[:, perm]
relHigh = relHigh[:, perm]
relClose = relClose[:, perm]

perm2 = np.random.permutation(ids)
relGap = relGap[:, perm2]

test = data.copy()

test.loc[:, (sym, "close")]
''''

SyntaxError: unterminated string literal (detected at line 14) (1138905052.py, line 14)

In [8]:
import pandas as pd 
df = pd.read_parquet("aapl_tsla_daily_2024.parquet")
df.index.

MultiIndex([('AAPL', '2024-01-02 09:00:00+00:00'),
            ('AAPL', '2024-01-02 09:01:00+00:00'),
            ('AAPL', '2024-01-02 09:02:00+00:00'),
            ('AAPL', '2024-01-02 09:03:00+00:00'),
            ('AAPL', '2024-01-02 09:04:00+00:00'),
            ('AAPL', '2024-01-02 09:05:00+00:00'),
            ('AAPL', '2024-01-02 09:06:00+00:00'),
            ('AAPL', '2024-01-02 09:07:00+00:00'),
            ('AAPL', '2024-01-02 09:08:00+00:00'),
            ('AAPL', '2024-01-02 09:09:00+00:00'),
            ...
            ('TSLA', '2024-01-06 00:49:00+00:00'),
            ('TSLA', '2024-01-06 00:51:00+00:00'),
            ('TSLA', '2024-01-06 00:52:00+00:00'),
            ('TSLA', '2024-01-06 00:53:00+00:00'),
            ('TSLA', '2024-01-06 00:54:00+00:00'),
            ('TSLA', '2024-01-06 00:55:00+00:00'),
            ('TSLA', '2024-01-06 00:56:00+00:00'),
            ('TSLA', '2024-01-06 00:57:00+00:00'),
            ('TSLA', '2024-01-06 00:58:00+00:00'),
            ('TSLA', '2024-01-06 00:59:00+00:00')],
           names=['symbol', 'timestamp'], length=6737)

In [42]:
aux = df.unstack(level="symbol").swaplevel(axis=1).sort_index(axis=1)
spread = 1
names = aux.columns.get_level_values("symbol").unique()
for name in names:
    aux.loc[:, (name, "bid")] = aux[name]["open"] - spread
aux.sort_index(axis=1)

symbol                         AAPL                                          \
                                bid     close      high       low      open
timestamp
2024-01-02 09:00:00+00:00  190.5200  190.2000  191.5200  190.0000  191.5200
2024-01-02 09:01:00+00:00  189.1100  190.0000  190.1300  190.0000  190.1100
2024-01-02 09:02:00+00:00  188.9000  189.8200  189.9000  189.8200  189.9000
2024-01-02 09:03:00+00:00  188.8700  189.8700  189.8700  189.8000  189.8700
2024-01-02 09:04:00+00:00  188.9000  189.9000  189.9500  189.9000  189.9000
...                             ...       ...       ...       ...       ...
2024-01-06 00:55:00+00:00  179.8000  180.8000  180.8000  180.8000  180.8000
2024-01-06 00:56:00+00:00  179.8001  180.8001  180.8001  180.8001  180.8001
2024-01-06 00:57:00+00:00  179.8100  180.7800  180.8100  180.7800  180.8100
2024-01-06 00:58:00+00:00  179.7500  180.7400  180.7600  180.7400  180.7500
2024-01-06 00:59:00+00:00  179.7800  180.7800  180.7800  180.7500  180.7800

symbol                                                        TSLA            \
                          trade_count   volume        vwap     bid     close
timestamp
2024-01-02 09:00:00+00:00       612.0  18933.0  190.241493  247.05  250.8800
2024-01-02 09:01:00+00:00       425.0   8562.0  190.088775  249.80  250.6400
2024-01-02 09:02:00+00:00       129.0   5355.0  189.823988  249.63  250.7400
2024-01-02 09:03:00+00:00        83.0   4405.0  189.859107  249.74  250.8700
2024-01-02 09:04:00+00:00        87.0   2225.0  189.916633  249.71  250.7500
...                               ...      ...         ...     ...       ...
2024-01-06 00:55:00+00:00        30.0   1024.0  180.800000  236.34  237.3300
2024-01-06 00:56:00+00:00        13.0    267.0  180.800100  236.33  237.3899
2024-01-06 00:57:00+00:00        41.0   1774.0  180.791558  236.35  237.3700
2024-01-06 00:58:00+00:00        43.0    887.0  180.747123  236.36  237.4000
2024-01-06 00:59:00+00:00        41.0   2149.0  180.758386  236.40  237.4000

symbol                                                                  \
                             high     low    open trade_count   volume
timestamp
2024-01-02 09:00:00+00:00  250.88  248.05  248.05       490.0  45689.0
2024-01-02 09:01:00+00:00  250.80  250.49  250.80       267.0   9704.0
2024-01-02 09:02:00+00:00  250.74  250.55  250.63       239.0  24077.0
2024-01-02 09:03:00+00:00  250.88  250.74  250.74       151.0  19369.0
2024-01-02 09:04:00+00:00  250.75  250.71  250.71        83.0   2055.0
...                           ...     ...     ...         ...      ...
2024-01-06 00:55:00+00:00  237.38  237.33  237.34        40.0   1515.0
2024-01-06 00:56:00+00:00  237.39  237.32  237.33        71.0   3585.0
2024-01-06 00:57:00+00:00  237.37  237.30  237.35        52.0   4815.0
2024-01-06 00:58:00+00:00  237.40  237.36  237.36        51.0   3756.0
2024-01-06 00:59:00+00:00  237.40  237.39  237.40        70.0   5467.0

symbol
                                 vwap
timestamp
2024-01-02 09:00:00+00:00  248.641496
2024-01-02 09:01:00+00:00  250.620665
2024-01-02 09:02:00+00:00  250.655699
2024-01-02 09:03:00+00:00  250.841022
2024-01-02 09:04:00+00:00  250.740588
...                               ...
2024-01-06 00:55:00+00:00  237.357500
2024-01-06 00:56:00+00:00  237.365234
2024-01-06 00:57:00+00:00  237.339598
2024-01-06 00:58:00+00:00  237.380920
2024-01-06 00:59:00+00:00  237.392615

[3723 rows x 16 columns]

In [37]:
spread = 1
names = aux.columns.get_level_values("symbol").unique()
for name in names:
    aux.loc[:, name, "bid"] = aux[name]["open"] - spread
aux

KeyError: "[slice(None, None, None), 'bid'] not in index"

In [6]:
df["bid_price"] = df["open"] + 0.01
df["ask_price"] = df["open"] - 0.01
df

                                      open      high       low     close  \
symbol timestamp
AAPL   2024-01-02 09:00:00+00:00  191.5200  191.5200  190.0000  190.2000
       2024-01-02 09:01:00+00:00  190.1100  190.1300  190.0000  190.0000
       2024-01-02 09:02:00+00:00  189.9000  189.9000  189.8200  189.8200
       2024-01-02 09:03:00+00:00  189.8700  189.8700  189.8000  189.8700
       2024-01-02 09:04:00+00:00  189.9000  189.9500  189.9000  189.9000
...                                    ...       ...       ...       ...
       2024-01-06 00:55:00+00:00  180.8000  180.8000  180.8000  180.8000
       2024-01-06 00:56:00+00:00  180.8001  180.8001  180.8001  180.8001
       2024-01-06 00:57:00+00:00  180.8100  180.8100  180.7800  180.7800
       2024-01-06 00:58:00+00:00  180.7500  180.7600  180.7400  180.7400
       2024-01-06 00:59:00+00:00  180.7800  180.7800  180.7500  180.7800

                                   volume  trade_count        vwap  bid_price  \
symbol timestamp
AAPL   2024-01-02 09:00:00+00:00  18933.0        612.0  190.241493   191.5300
       2024-01-02 09:01:00+00:00   8562.0        425.0  190.088775   190.1200
       2024-01-02 09:02:00+00:00   5355.0        129.0  189.823988   189.9100
       2024-01-02 09:03:00+00:00   4405.0         83.0  189.859107   189.8800
       2024-01-02 09:04:00+00:00   2225.0         87.0  189.916633   189.9100
...                                   ...          ...         ...        ...
       2024-01-06 00:55:00+00:00   1024.0         30.0  180.800000   180.8100
       2024-01-06 00:56:00+00:00    267.0         13.0  180.800100   180.8101
       2024-01-06 00:57:00+00:00   1774.0         41.0  180.791558   180.8200
       2024-01-06 00:58:00+00:00    887.0         43.0  180.747123   180.7600
       2024-01-06 00:59:00+00:00   2149.0         41.0  180.758386   180.7900

                                  ask_price
symbol timestamp
AAPL   2024-01-02 09:00:00+00:00   191.5100
       2024-01-02 09:01:00+00:00   190.1000
       2024-01-02 09:02:00+00:00   189.8900
       2024-01-02 09:03:00+00:00   189.8600
       2024-01-02 09:04:00+00:00   189.8900
...                                     ...
       2024-01-06 00:55:00+00:00   180.7900
       2024-01-06 00:56:00+00:00   180.7901
       2024-01-06 00:57:00+00:00   180.8000
       2024-01-06 00:58:00+00:00   180.7400
       2024-01-06 00:59:00+00:00   180.7700

[3143 rows x 9 columns]

In [ ]:
class InfoCreate():
    def __init__(self, file_paths, symbols, start, end, whereToSave, spread):
        self.file_paths = file_paths
        self.symbols = symbols
        self.start = start
        self.end = end
        self.spread = spread
        self.whereToSave = whereToSave

    def get_data(self):
        frames = []
        for name in self.file_paths:
            frames.append(pd.read_parquet(name))
        aux = pd.concat(frames).sort_index()
        aux = aux[aux.index.get_level_values("symbol").isin(self.symbols)]
        aux = aux[~aux.index.duplicated(keep="last")]
        aux = aux.unstack("symbol").swaplevel(axis=1).sort_index(axis=1)

        self.data = aux.ffill().loc[self.start:self.end].copy()
        names = self.data.columns.get_level_values("symbol").unique()
        for name in names:
            o = self.data[name]["open"]
            self.data.loc[:, (name, "bid")] = o - self.spread
            self.data.loc[:, (name, "ask")] = o + self.spread
        self.data = self.data.sort_index(axis=1)

        if self.whereToSave is not None:
            self.data.to_parquet("{}.parquet".(self.whereToSave))