In [7]:
import pandas as pd

df = pd.read_parquet("aapl_tsla_daily_2024.parquet")
df

                                    open    high     low     close   volume  \
symbol timestamp
AAPL   2024-01-02 09:00:00+00:00  191.52  191.52  190.00  190.2000  18933.0
       2024-01-02 09:01:00+00:00  190.11  190.13  190.00  190.0000   8562.0
       2024-01-02 09:02:00+00:00  189.90  189.90  189.82  189.8200   5355.0
       2024-01-02 09:03:00+00:00  189.87  189.87  189.80  189.8700   4405.0
       2024-01-02 09:04:00+00:00  189.90  189.95  189.90  189.9000   2225.0
...                                  ...     ...     ...       ...      ...
TSLA   2024-01-06 00:55:00+00:00  237.34  237.38  237.33  237.3300   1515.0
       2024-01-06 00:56:00+00:00  237.33  237.39  237.32  237.3899   3585.0
       2024-01-06 00:57:00+00:00  237.35  237.37  237.30  237.3700   4815.0
       2024-01-06 00:58:00+00:00  237.36  237.40  237.36  237.4000   3756.0
       2024-01-06 00:59:00+00:00  237.40  237.40  237.39  237.4000   5467.0

                                  trade_count        vwap
symbol timestamp
AAPL   2024-01-02 09:00:00+00:00        612.0  190.241493
       2024-01-02 09:01:00+00:00        425.0  190.088775
       2024-01-02 09:02:00+00:00        129.0  189.823988
       2024-01-02 09:03:00+00:00         83.0  189.859107
       2024-01-02 09:04:00+00:00         87.0  189.916633
...                                       ...         ...
TSLA   2024-01-06 00:55:00+00:00         40.0  237.357500
       2024-01-06 00:56:00+00:00         71.0  237.365234
       2024-01-06 00:57:00+00:00         52.0  237.339598
       2024-01-06 00:58:00+00:00         51.0  237.380920
       2024-01-06 00:59:00+00:00         70.0  237.392615

[6737 rows x 7 columns]

In [42]:
aux = df.unstack(level="symbol").swaplevel(axis=1).sort_index(axis=1)
spread = 1
names = aux.columns.get_level_values("symbol").unique()
for name in names:
    aux.loc[:, (name, "bid")] = aux[name]["open"] - spread
aux.sort_index(axis=1)

symbol                         AAPL                                          \
                                bid     close      high       low      open
timestamp
2024-01-02 09:00:00+00:00  190.5200  190.2000  191.5200  190.0000  191.5200
2024-01-02 09:01:00+00:00  189.1100  190.0000  190.1300  190.0000  190.1100
2024-01-02 09:02:00+00:00  188.9000  189.8200  189.9000  189.8200  189.9000
2024-01-02 09:03:00+00:00  188.8700  189.8700  189.8700  189.8000  189.8700
2024-01-02 09:04:00+00:00  188.9000  189.9000  189.9500  189.9000  189.9000
...                             ...       ...       ...       ...       ...
2024-01-06 00:55:00+00:00  179.8000  180.8000  180.8000  180.8000  180.8000
2024-01-06 00:56:00+00:00  179.8001  180.8001  180.8001  180.8001  180.8001
2024-01-06 00:57:00+00:00  179.8100  180.7800  180.8100  180.7800  180.8100
2024-01-06 00:58:00+00:00  179.7500  180.7400  180.7600  180.7400  180.7500
2024-01-06 00:59:00+00:00  179.7800  180.7800  180.7800  180.7500  180.7800

symbol                                                        TSLA            \
                          trade_count   volume        vwap     bid     close
timestamp
2024-01-02 09:00:00+00:00       612.0  18933.0  190.241493  247.05  250.8800
2024-01-02 09:01:00+00:00       425.0   8562.0  190.088775  249.80  250.6400
2024-01-02 09:02:00+00:00       129.0   5355.0  189.823988  249.63  250.7400
2024-01-02 09:03:00+00:00        83.0   4405.0  189.859107  249.74  250.8700
2024-01-02 09:04:00+00:00        87.0   2225.0  189.916633  249.71  250.7500
...                               ...      ...         ...     ...       ...
2024-01-06 00:55:00+00:00        30.0   1024.0  180.800000  236.34  237.3300
2024-01-06 00:56:00+00:00        13.0    267.0  180.800100  236.33  237.3899
2024-01-06 00:57:00+00:00        41.0   1774.0  180.791558  236.35  237.3700
2024-01-06 00:58:00+00:00        43.0    887.0  180.747123  236.36  237.4000
2024-01-06 00:59:00+00:00        41.0   2149.0  180.758386  236.40  237.4000

symbol                                                                  \
                             high     low    open trade_count   volume
timestamp
2024-01-02 09:00:00+00:00  250.88  248.05  248.05       490.0  45689.0
2024-01-02 09:01:00+00:00  250.80  250.49  250.80       267.0   9704.0
2024-01-02 09:02:00+00:00  250.74  250.55  250.63       239.0  24077.0
2024-01-02 09:03:00+00:00  250.88  250.74  250.74       151.0  19369.0
2024-01-02 09:04:00+00:00  250.75  250.71  250.71        83.0   2055.0
...                           ...     ...     ...         ...      ...
2024-01-06 00:55:00+00:00  237.38  237.33  237.34        40.0   1515.0
2024-01-06 00:56:00+00:00  237.39  237.32  237.33        71.0   3585.0
2024-01-06 00:57:00+00:00  237.37  237.30  237.35        52.0   4815.0
2024-01-06 00:58:00+00:00  237.40  237.36  237.36        51.0   3756.0
2024-01-06 00:59:00+00:00  237.40  237.39  237.40        70.0   5467.0

symbol
                                 vwap
timestamp
2024-01-02 09:00:00+00:00  248.641496
2024-01-02 09:01:00+00:00  250.620665
2024-01-02 09:02:00+00:00  250.655699
2024-01-02 09:03:00+00:00  250.841022
2024-01-02 09:04:00+00:00  250.740588
...                               ...
2024-01-06 00:55:00+00:00  237.357500
2024-01-06 00:56:00+00:00  237.365234
2024-01-06 00:57:00+00:00  237.339598
2024-01-06 00:58:00+00:00  237.380920
2024-01-06 00:59:00+00:00  237.392615

[3723 rows x 16 columns]

In [37]:
spread = 1
names = aux.columns.get_level_values("symbol").unique()
for name in names:
    aux.loc[:, name, "bid"] = aux[name]["open"] - spread
aux

KeyError: "[slice(None, None, None), 'bid'] not in index"

In [6]:
df["bid_price"] = df["open"] + 0.01
df["ask_price"] = df["open"] - 0.01
df

                                      open      high       low     close  \
symbol timestamp
AAPL   2024-01-02 09:00:00+00:00  191.5200  191.5200  190.0000  190.2000
       2024-01-02 09:01:00+00:00  190.1100  190.1300  190.0000  190.0000
       2024-01-02 09:02:00+00:00  189.9000  189.9000  189.8200  189.8200
       2024-01-02 09:03:00+00:00  189.8700  189.8700  189.8000  189.8700
       2024-01-02 09:04:00+00:00  189.9000  189.9500  189.9000  189.9000
...                                    ...       ...       ...       ...
       2024-01-06 00:55:00+00:00  180.8000  180.8000  180.8000  180.8000
       2024-01-06 00:56:00+00:00  180.8001  180.8001  180.8001  180.8001
       2024-01-06 00:57:00+00:00  180.8100  180.8100  180.7800  180.7800
       2024-01-06 00:58:00+00:00  180.7500  180.7600  180.7400  180.7400
       2024-01-06 00:59:00+00:00  180.7800  180.7800  180.7500  180.7800

                                   volume  trade_count        vwap  bid_price  \
symbol timestamp
AAPL   2024-01-02 09:00:00+00:00  18933.0        612.0  190.241493   191.5300
       2024-01-02 09:01:00+00:00   8562.0        425.0  190.088775   190.1200
       2024-01-02 09:02:00+00:00   5355.0        129.0  189.823988   189.9100
       2024-01-02 09:03:00+00:00   4405.0         83.0  189.859107   189.8800
       2024-01-02 09:04:00+00:00   2225.0         87.0  189.916633   189.9100
...                                   ...          ...         ...        ...
       2024-01-06 00:55:00+00:00   1024.0         30.0  180.800000   180.8100
       2024-01-06 00:56:00+00:00    267.0         13.0  180.800100   180.8101
       2024-01-06 00:57:00+00:00   1774.0         41.0  180.791558   180.8200
       2024-01-06 00:58:00+00:00    887.0         43.0  180.747123   180.7600
       2024-01-06 00:59:00+00:00   2149.0         41.0  180.758386   180.7900

                                  ask_price
symbol timestamp
AAPL   2024-01-02 09:00:00+00:00   191.5100
       2024-01-02 09:01:00+00:00   190.1000
       2024-01-02 09:02:00+00:00   189.8900
       2024-01-02 09:03:00+00:00   189.8600
       2024-01-02 09:04:00+00:00   189.8900
...                                     ...
       2024-01-06 00:55:00+00:00   180.7900
       2024-01-06 00:56:00+00:00   180.7901
       2024-01-06 00:57:00+00:00   180.8000
       2024-01-06 00:58:00+00:00   180.7400
       2024-01-06 00:59:00+00:00   180.7700

[3143 rows x 9 columns]

In [ ]:
class InfoCreate():
    def __init__(self, file_paths, symbols, start, end, whereToSave, spread):
        self.file_paths = file_paths
        self.symbols = symbols
        self.start = start
        self.end = end
        self.spread = spread
        self.whereToSave = whereToSave

    def get_data(self):
        frames = []
        for name in self.file_paths:
            frames.append(pd.read_parquet(name))
        aux = pd.concat(frames).sort_index()
        aux = aux[aux.index.get_level_values("symbol").isin(self.symbols)]
        aux = aux[~aux.index.duplicated(keep="last")]
        aux = aux.unstack("symbol").swaplevel(axis=1).sort_index(axis=1)

        self.data = aux.ffill().loc[self.start:self.end].copy()
        names = self.data.columns.get_level_values("symbol").unique()
        for name in names:
            o = self.data[name]["open"]
            self.data.loc[:, (name, "bid")] = o - self.spread
            self.data.loc[:, (name, "ask")] = o + self.spread
        self.data = self.data.sort_index(axis=1)

        if self.whereToSave is not None:
            self.data.to_parquet("{}.parquet".(self.whereToSave))